"""empty message

Revision ID: 43182ec1ae06
Revises: 4402d25721a9
Create Date: 2020-04-12 08:52:36.349074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43182ec1ae06'
down_revision = '4402d25721a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('address', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('volunteer_status', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_user_address'), 'user', ['address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_address'), table_name='user')
    op.drop_column('user', 'volunteer_status')
    op.drop_column('user', 'address')
    # ### end Alembic commands ###
